apiVersion: v1
kind: ConfigMap
metadata:
  name: arkime-sensor-rules
  namespace: arkime
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  rules.txt: |
    ---
    version: 1
    rules:
    - name: "Only save first 20 packets of TLS sessions"
      when: "fieldSet"
      fields:
        protocols:
        - tls
      ops:
        _maxPacketsToSave: 20
    
    - name: "Drop to localhost"
      when: "fieldSet"
      fields:
        ip.src:
        - 127.0.0.1
      ops:
        _maxPacketsToSave: 10
    
    - name: "Drop from localhost"
      when: "fieldSet"
      fields:
        ip.dst:
        - 127.0.0.1
      ops:
        _maxPacketsToSave: 10