name: Build Arkime Image
run-name: ${{github.actor}} is building the Arkime Container Image
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
    tags: ["v**"]

permissions:
  id-token: write
  contents: read

env:
  REF_NAME: "${{ github.head_ref || github.ref_name }}"
  REF_TYPE: "${{ github.ref_type }}"
  IMAGE_NAME: 765814079306.dkr.ecr.us-east-1.amazonaws.com/arkime4
  IMAGE_TAG: "${{ github.head_ref || github.ref_name }}"
  ZARF_PACKAGE: zarf-package-arkime-amd64.tar.zst
  BB_MIN_PACKAGE: zarf-package-dco-foundation-amd64.tar.zst
  IMAGE_S3_PATH: "s3://${{ secrets.AWS_ASSETS_BUCKET }}/arkime/"

jobs:
  image-create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS ECR Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          role-session-name: arkime-ecr
          aws-region: us-east-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Configure AWS S3 Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: arkime-s3
          aws-region: us-east-1

      - name: Copy build assets from S3
        run: |
          mkdir -p assets
          aws s3 cp --no-progress "${{ env.IMAGE_S3_PATH }}" assets --recursive

      - name: Build Image
        run: |
          IMAGE_TAG="${{ env.IMAGE_TAG }}"
          IMAGE_TAG=${IMAGE_TAG//\//\_}
          docker build -t "${{ env.IMAGE_NAME }}":"$IMAGE_TAG" .

      - name: Publish to ECR
        run: |
          IMAGE_TAG="${{ env.IMAGE_TAG }}"
          IMAGE_TAG=${IMAGE_TAG//\//\_}
          docker push "${{ env.IMAGE_NAME }}":"$IMAGE_TAG"

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build and Push Image to ECR
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: "${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}"